"""Throwaway `fleet status` table + `FLEET.md` generator (PLAN.md Chunk 6, FR-7/CC-7).

Both entry points here are pure **views**: they read every tracked session's
five decomposed status fields (`core.schema.STATUS_FIELDS`) plus its
dependency edges exclusively through `core.query` (and `core.query.edges_of`,
a thin filter over `core.edges.resolve_graph`) — never by re-reading fragment
files or the event log directly, and never by importing anything that writes
the manifest (`core.events.append`, `core.store.write_fragment`,
`core.projection.project_event`/`rebuild`). `gen-view` writes a *generated
doc* (`docs/superhuman/<slug>/FLEET.md`, DESIGN "Decision A") — that is not
the manifest (`events.jsonl` / per-session fragments / `.lock`), so it is not
a violation of the read-only contract this module is built to satisfy.

This is explicitly a disposable viewer, superseded by a future Phase-2
dashboard (PLAN.md Chunk 6 note) — kept intentionally simple: one table
renderer, one Markdown generator, no caching, no incremental update.
"""

from __future__ import annotations

from pathlib import Path

from .core.query import edges_of, list_sessions
from .core.schema import Fragment

#: Column order for both the CLI table and the FLEET.md table — the five
#: decomposed status fields (FR-5), in `core.schema.STATUS_FIELDS` order,
#: plus identity and a rendered edges column.
_COLUMNS: tuple[str, ...] = (
    "node_id",
    "lifecycle",
    "block_state",
    "review_state",
    "adoption_state",
    "done_level",
    "edges",
)

#: Marker line prefixing the FLEET.md generated-doc header, so a human
#: skimming the file immediately knows it is regenerated, not hand-authored
#: (mirrors the caution every other generated artifact in this package
#: carries — e.g. `core/store.py`'s fragment files are never hand-edited
#: either).
_GENERATED_HEADER_NOTE = (
    "Generated by `fleet gen-view` from `core/query` — do not edit by hand; "
    "re-run `fleet gen-view` after the manifest changes."
)


def _format_edge(node_id: str, edge: dict) -> str:
    """Render one `core.query.edges_of` edge dict from `node_id`'s point of view.

    Args:
        node_id: the session this edge is being rendered for.
        edge: one edge dict as returned by `core.query.edges_of`
            (`src`, `type`, `dst`, `source`, `evidence`).

    Returns:
        str: `"<type>-> <dst> (<source>)"` if `node_id` is the edge's `src`,
        or `"<-<type> <src> (<source>)"` if `node_id` is the `dst` — so the
        direction is legible from a single node's row without needing the
        full graph alongside it.
    """
    if edge["src"] == node_id:
        return f"{edge['type']}-> {edge['dst']} ({edge['source']})"
    return f"<-{edge['type']} {edge['src']} ({edge['source']})"


def collect_rows(
    sessions_dir: Path | str, log_path: Path | str, *, project_id: str | None = None
) -> list[dict[str, str]]:
    """Build one render-ready row per tracked session, in deterministic order.

    Reads exclusively via `core.query.list_sessions` (fragments) and
    `core.query.edges_of` (dependency edges) — no direct fragment/log access.

    Args:
        sessions_dir: the project's fragment directory.
        log_path: the project's event log (edges are derived from this).
        project_id: if given, only sessions with this exact `project_id`
            (equality, per `list_sessions`'s own G3-1 contract).

    Returns:
        list[dict[str, str]]: one dict per session, keyed by `_COLUMNS`,
        sorted by `node_id` for a reproducible, diff-stable rendering — the
        order `iter_fragments` returns (filename/percent-encoding order) is
        an implementation detail of `core/store.py`, not a rendering
        contract, so this re-sorts explicitly rather than relying on it.
    """
    fragments: list[Fragment] = list_sessions(sessions_dir, project_id=project_id)
    rows: list[dict[str, str]] = []
    for fragment in sorted(fragments, key=lambda f: f.node_id):
        edges = edges_of(fragment.node_id, log_path)
        edges_text = "; ".join(
            _format_edge(fragment.node_id, e)
            for e in sorted(edges, key=lambda e: (e["type"], e["src"], e["dst"]))
        )
        rows.append(
            {
                "node_id": fragment.node_id,
                "lifecycle": fragment.lifecycle,
                "block_state": fragment.block_state,
                "review_state": fragment.review_state,
                "adoption_state": fragment.adoption_state,
                "done_level": fragment.done_level,
                "edges": edges_text,
            }
        )
    return rows


def render_status_table(
    sessions_dir: Path | str, log_path: Path | str, *, project_id: str | None = None
) -> str:
    """Render `fleet status`'s plain-text table.

    Args:
        sessions_dir: the project's fragment directory.
        log_path: the project's event log.
        project_id: optional exact-match filter (see `collect_rows`).

    Returns:
        str: a fixed-width, space-padded table with one header line and one
        line per session (widest cell per column, `_COLUMNS` order); a single
        `"no tracked sessions"` line if there are none. Never ends with a
        trailing newline (the caller `print()`s it).
    """
    rows = collect_rows(sessions_dir, log_path, project_id=project_id)
    if not rows:
        return "no tracked sessions"

    widths = {
        col: max(len(col), *(len(row[col]) for row in rows)) for col in _COLUMNS
    }
    header = "  ".join(col.upper().ljust(widths[col]) for col in _COLUMNS)
    separator = "  ".join("-" * widths[col] for col in _COLUMNS)
    lines = [header, separator]
    for row in rows:
        lines.append("  ".join(row[col].ljust(widths[col]) for col in _COLUMNS))
    return "\n".join(lines)


def render_fleet_md(
    sessions_dir: Path | str,
    log_path: Path | str,
    *,
    slug: str,
    project_id: str | None = None,
) -> str:
    """Render the `FLEET.md` generated view (DESIGN "Decision A").

    A standalone Markdown document — never a section spliced into the
    human-authored `SUPERHUMAN.md` (Decision A explicitly rejects that: "a
    generated artifact should not churn the human-authored SUPERHUMAN.md").
    Deterministic: calling this twice against an unchanged manifest produces
    byte-identical output — no wall-clock timestamp or other non-manifest
    input is embedded (FR-7/CC-7's read-only view carries no state of its
    own to make stale).

    Args:
        sessions_dir: the project's fragment directory.
        log_path: the project's event log.
        slug: the superhuman project slug, used only in the document title.
        project_id: optional exact-match filter (see `collect_rows`).

    Returns:
        str: the full Markdown document, ending with a trailing newline.
    """
    rows = collect_rows(sessions_dir, log_path, project_id=project_id)

    lines = [f"# Fleet: {slug}", "", _GENERATED_HEADER_NOTE, ""]

    if not rows:
        lines.append("_No tracked sessions._")
        lines.append("")
        return "\n".join(lines)

    header_cells = [col.replace("_", " ") for col in _COLUMNS]
    lines.append("| " + " | ".join(header_cells) + " |")
    lines.append("| " + " | ".join("---" for _ in _COLUMNS) + " |")
    for row in rows:
        cells = [_escape_md_cell(row[col]) for col in _COLUMNS]
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    return "\n".join(lines)


def _escape_md_cell(value: str) -> str:
    """Escape a value for safe embedding in one Markdown table cell.

    Args:
        value: the raw cell text (a node id, status value, or rendered edge
            list — any of which may legally be empty, but never contain a
            literal newline per this package's own schema, DP#5).

    Returns:
        str: `value` with any `|` escaped (the one character that would
        otherwise break table-cell parsing) and empty replaced by an
        explicit em-dash placeholder so an empty edges column still renders
        as a visible cell rather than a blank one that looks like a parse
        error.
    """
    escaped = value.replace("|", "\\|")
    return escaped if escaped else "—"


def write_fleet_md(
    sessions_dir: Path | str,
    log_path: Path | str,
    *,
    slug: str,
    workspace: Path | str,
    project_id: str | None = None,
) -> Path:
    """Generate and write `docs/superhuman/<slug>/FLEET.md` (DESIGN "Decision A").

    Writes only the generated *doc* — never the manifest. This function
    imports nothing from `core.events`/`core.store`/`core.projection`'s write
    surfaces and never opens `events.jsonl`, a fragment file, or `.lock` for
    writing; `render_fleet_md` above is a pure read/render step, and this
    wrapper's only write is to the FLEET.md path itself.

    Args:
        sessions_dir: the project's fragment directory.
        log_path: the project's event log.
        slug: the superhuman project slug — both the document title and the
            path component (`docs/superhuman/<slug>/FLEET.md`).
        workspace: the project's working-tree root; the FLEET.md path is
            resolved beneath it, beside `SUPERHUMAN.md` (Decision A).
        project_id: optional exact-match filter (see `collect_rows`).

    Returns:
        Path: the FLEET.md path written.
    """
    content = render_fleet_md(sessions_dir, log_path, slug=slug, project_id=project_id)
    target = Path(workspace) / "docs" / "superhuman" / slug / "FLEET.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return target
